# alias python="python3 $@"
# alias emacs="emacs &"
alias ll="ls --color=auto -lh --group-directories-first"
alias lls="ls --color=auto -lh --group-directories-first"
alias la="ls --color=auto -Ah --group-directories-first"
alias lla="ls --color=auto -lAh --group-directories-first"
alias grep='grep --color=auto'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias nv="nvim $@"
alias t="dstask"
